#На основе рекомендаций от фирменного Postgres
#Юзер Postgres`а: postgres
version: "3.8"

services:

  db:
    image: postgres:13.6-alpine3.15
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-volume:
